### ISSUE TITLE
Allow setting foreground and background independently of 0-15

### ISSUE THREAD

**Issue by courtyardz** [dylanaraps/paleta#2]
This is a brilliant utility for seamlessly changing color theme across xterms. How `pal` sends command sequences works much better than what I had been trying: calling `xdotool search --class xterm` to create a stack of xterm windows and then calling xdotool again to send (after changing the dubious xterm*AllowSendEvents setting) each xterm `xtermcontrol` commands that change the colors... *ugh*. Not a good solution. I want to use a tool like `pal` that works with command sequences directly.

For my use, I am trying to use `pal` to switch all xterms between Solarized Dark and Solarized Light themes.  As far as I can tell, these themes require slightly more complex sequences than your utility currently allows. The foreground and background colors cannot simply be assumed to be colors 0 and 15, and other settings like the cursor color must be set to specific values.

Per the [official Solarized repo](https://github.com/solarized/xresources/blob/master/Xresources.dark), the Solarized dark color scheme is specified as follows in a `Xresources` file:

```
#define S_base03        #002b36
#define S_base02        #073642
#define S_base01        #586e75
#define S_base00        #657b83
#define S_base0         #839496
#define S_base1         #93a1a1
#define S_base2         #eee8d5
#define S_base3         #fdf6e3
#define S_yellow        #b58900
#define S_orange        #cb4b16
#define S_red           #dc322f
#define S_magenta       #d33682
#define S_violet        #6c71c4
#define S_blue          #268bd2
#define S_cyan          #2aa198
#define S_green         #859900

!mappings
*background:            S_base03
*foreground:            S_base0
*fadeColor:             S_base03
*cursorColor:           S_base1
*pointerColorBackground:S_base01
*pointerColorForeground:S_base1

!! black dark/light
*color0:                S_base02
*color8:                S_base03

!! red dark/light
*color1:                S_red
*color9:                S_orange

!! green dark/light
*color2:                S_green
*color10:               S_base01

!! yellow dark/light
*color3:                S_yellow
*color11:               S_base00

!! blue dark/light
*color4:                S_blue
*color12:               S_base0

!! magenta dark/light
*color5:                S_magenta
*color13:               S_violet

!! cyan dark/light
*color6:                S_cyan
*color14:               S_base1

!! white dark/light
*color7:                S_base2
*color15: 		S_base3
```

So, I assume my next step would be to fork `pal`, in which I alter the following lines of `make_sequences()`:

```
    # 10: Foreground color,
    # 11: Background color,
    # 12: Cursor Foreground color.
    # Source: https://goo.gl/KcoQgP
    sequences+="\\e]10;${colors[15]}\\e\\\\"
    sequences+="\\e]11;${colors[0]}\\e\\\\"
    sequences+="\\e]12;${colors[15]}\\e\\\\"
```
to set the correct `background`, `foreground`, `pointerColorForeground` values. I would then add similar lines that set `fadeColor`, `cursorColor`, and `pointerColorBackground` to the Solarized spec as well. 

Thanks for any help/suggestions. Just thinking out loud. I would like to make pal's magic available to Solarized users wishing for a sane way to switch all their xterms to dark themes at sundown and light themes at sunup!

**Comment by dylanaraps** [comment]
This should work: 

```
#073642
#dc322f
#859900
#b58900
#268bd2
#d33682
#2aa198
#eee8d5
#002b36
#cb4b16
#586e75
#657b83
#839496
#6c71c4
#93a1a1
#fdf6e3
```

The only real thing `pal` is missing is the ability to set `background`, `foreground` and `cursor` colors independently.

**Comment by courtyardz** [comment]
Cool, I came up with the same color sequence to feed `pal` as you. It's almost a match. `foreground` ("default" in the screenshots) is set, as expected, incorrectly to color15. I'll link to my fork of `pal` here if/when I hack it.

Colors via `.Xresources`:
![2019-02-23-110238_664x583_scrot](https://user-images.githubusercontent.com/10345884/53289062-f6e27300-375e-11e9-9d13-a91316e994d5.png)

Colors via `pal`:
![2019-02-23-110235_664x583_scrot](https://user-images.githubusercontent.com/10345884/53289065-0366cb80-375f-11e9-9c6c-8234264a50e4.png)

Thanks again!

**Comment by dylanaraps** [comment]
Its just a matter of adding the ability to set background/foreground/cursor independent of colors `0-15`. Will work on this :+1:

**Comment by dylanaraps** [comment]
Rewrote paleta in C. Documentation still to follow. 

In short:

- It now supports setting background, foreground and cursor independently.
- It now supports setting the entire terminal palette.
- Input is now solely over stdin which is still flexible and versatile.

Usage:

- Lines `1-3` over stdin control background, foreground and cursor accordingly.
- Lines `4-<COMPILE TIME MAXIMUM>` (default to `256`) control the terminal's numerical palette. 

Example input:

```
<fg>
<bg>
<cursor>
<colors 0-256> (or whatever compile time maximum is chosen)
```

Let me know if you have anymore questions. Will make a release shortly.
