### ISSUE TITLE
Messed up colors in termite

### ISSUE THREAD

**Issue by kayew** [dylanaraps/paleta#3]
When setting the colors through pal in termite, the color scheme becomes messed up. When attempting to set a theme such as materia, the output is completely different than what its supposed to, with the colors being in the wrong places.

**Comment by dylanaraps** [comment]
Can you reproduce this with master?

**Comment by kayew** [comment]
Ok, I've updated to the latest commit and gave it a go. It's still broken.

![broken paleta](http://i.salejandro.me/1Uwmx.png)

Here's the file `gruvbox_dark_hard`:
```
#1d2021
#3c3836
#504945
#665c54
#bdae93
#d5c4a1
#ebdbb2
#fbf1c7
#fb4934
#fe8019
#fabd2f
#b8bb26
#8ec07c
#83a598
#d3869b
#d65d0e
```

**Comment by dylanaraps** [comment]
Issue should no longer occur.

**Comment by dylanaraps** [comment]
See: https://github.com/dylanaraps/paleta/issues/2#issuecomment-667016102
